### ISSUE TITLE
Different behavior between git-lfs client 0.6.0 and 0.5.4

### ISSUE THREAD

**Issue by isserrano** [cloudmazing/lfs-server-go#8]
When doing a git push with 0.5.4:
```
$git push origin
ismaels@gitlfs-client:/local/mnt/gitrepos/reponame.git$ git push --set-upstream origin master
Username for 'http://gitlfs-server:9999': repo
Password for 'http://repo@gitlfs-server:9999': 
(283 of 283 files) 22.29 MB 29s
Counting objects: 8132, done.
Compressing objects: 100% (4205/4205), done.
Writing objects: 100% (8132/8132), 231.18 MiB | 200.97 MiB/s, done.
Total 8132 (delta 3348), reused 8132 (delta 3348)
Username for 'http://gitlfs-server:80': repo
Password for 'http://repo@gitlfs-server:80': 
Everything up-to-date
$ git lfs version
git-lfs/0.5.4 (GitHub; linux amd64; go 1.3; git b00fa51)
```

But when using 0.6.0 it does not even try to connect to the git lfs server:

```
$ git push origin
Counting objects: 8135, done.
Compressing objects: 100% (4208/4208), done.
Writing objects: 100% (8135/8135), 231.18 MiB | 142.66 MiB/s, done.
Total 8135 (delta 3349), reused 8131 (delta 3348)
Username for 'http://gitlfs-server:80': repo
Password for 'http://repo@gitlfs-server:80': 
Everything up-to-date
$ git lfs version
git-lfs/0.6.0 (GitHub; linux amd64; go 1.5.1; git 183bdc8)
```

Should all the clients work?
Should have I different configuration depending on the client?

Repository config:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true

[lfs]
        url = "http://gitlfs-server:9999/repo/reponame.git"
	batch = true

[http]
        sslverify = false
	postBuffer = 524288000
[remote "origin"]
	url = "http://gitlfs-server:80/repo/reponame.git"
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "test"]
	remote = origin
	merge = refs/heads/test
[branch "test2"]
	remote = origin
	merge = refs/heads/test2
[lfs "http://gitlfs-server:9999/repo/reponame.git"]
	access = private
```

**Comment by memikequinn** [comment]
It looks like a client issue, 0.5.4 and 0.6.0 work for me.  If you're adding a lot of files, then you'll see this error when running `git lfs ls-files` 

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/github/git-lfs/git.ResolveRef(0x882d90, 0x4, 0x1, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/git/git.go:68 +0x2f6
github.com/github/git-lfs/git.CurrentRef(0xacf3a0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/git/git.go:73 +0x38
github.com/github/git-lfs/commands.lsFilesCommand(0xaa55c0, 0xacf3a0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_ls_files.go:26 +0x205
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xaa55c0, 0xacf3a0, 0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xaa6ae0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:85 +0x23
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x14
```

I assume the client is doing the same thing and puking.  Please open an issue with the LFS Client and reopen this issue if you find there is not an issue with the client. thanks!
